// <auto-generated />
using System;
using FocusFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FocusFlowDbContext))]
    [Migration("20260716184244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("FocusFlow.Domain.Presets.PomodoroPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStartBreaks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_start_breaks");

                    b.Property<bool>("AutoStartFocusSessions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_start_focus_sessions");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<string>("CycleSettings")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cycle_settings_json");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ticks");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("pomodoro_presets", (string)null);
                });

            modelBuilder.Entity("FocusFlow.Domain.Projects.FocusProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived_at_utc_ticks");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc_ticks");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ticks");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("focus_projects", (string)null);
                });

            modelBuilder.Entity("FocusFlow.Domain.Sessions.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualDuration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actual_duration_ticks");

                    b.Property<long?>("CancelledAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancelled_at_utc_ticks");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc_ticks");

                    b.Property<int>("CompletionReason")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion_reason");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<long?>("ExpectedEndAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expected_end_at_utc_ticks");

                    b.Property<long?>("PausedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paused_at_utc_ticks");

                    b.Property<long>("PlannedDuration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planned_duration_ticks");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("preset_id");

                    b.Property<long>("RemainingDuration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remaining_duration_ticks");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc_ticks");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ticks");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskId");

                    b.ToTable("focus_sessions", (string)null);
                });

            modelBuilder.Entity("FocusFlow.Domain.Tasks.FocusTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CancelledAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancelled_at_utc_ticks");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc_ticks");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ticks");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Estimate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estimated_pomodoros");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc_ticks");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ticks");

                    b.Property<string>("_completedFocusSessionIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_focus_session_ids_json");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("focus_tasks", (string)null);
                });

            modelBuilder.Entity("FocusFlow.Domain.Sessions.FocusSession", b =>
                {
                    b.HasOne("FocusFlow.Domain.Presets.PomodoroPreset", null)
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FocusFlow.Domain.Tasks.FocusTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FocusFlow.Domain.Tasks.FocusTask", b =>
                {
                    b.HasOne("FocusFlow.Domain.Projects.FocusProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
